### PR TITLE
gzip support + cutom headers

### PR DESCRIPTION
**Pull request by SelvinPL**
- added gzip support (only for !WINDOWS_PHONE)
- added custom headers 

in both cases you can access it via CacheControllerBehavior:
gzip: set AutomaticDecompression to true
custom header: use AddCustomHeaders(key, value)

also I modified .gitignore becuase of "packages" folder

### CODE REVIEW

**Comment by gentledepp** [comment]
Has not been a lot going on here. However, the custom headers feature is a very important requirement for us, as we use bearer tokens to do authentication.
Is this project still active?

**Comment by vikingau** [comment]
Well, I use the core code in a Xamarin based app, and I would like to see the various changes pulled into the master. That said, you can make your own local copy and manage it yourself, which is what I have done because this project is very quiet.  Come on Mimetis, how about rebooting this project...

**Comment by gentledepp** [comment]
Yes, @Mimetis  - or at least add someone else as an additional contributor. We don't want this project to become stale...

**Comment by Mimetis** [comment]
Hi guys.
Sorry to be so quiet lately, I have no excuses, to be honest ...
I will update the master branch with all your commits, after doing some quick tests.
For additional contributor, you are so right.
If some of you guys wants to join the project as contributor, feel free to contact me, it will be a real pleasure for me !

**Comment by gentledepp** [comment]
feel contacted...

**Comment by Mimetis** [comment]
I added you as Collaborator :)

**Comment by vikingau** [comment]
Thankyou.

 

Thanks very much for the framework – it is excellent.

 

Geoff

**Pull request merged**
