### PR TITLE
Several additions

### PR DESCRIPTION
**Pull request by gentledepp**
Split nuget package to a server- and a client part
That way, you can include the client-package in a test project and write integation tests which is what I recommend, when you use such a complex framework.

Also, we added support for specifying the full path to a database file, not just the database name. This is usable in automated tests where you have your databases in the testdata, or bin-folder of your testproject.

Also fixed a nullreferenceexception in the CacheControllerBehavior.

Also, this PR includes the additions to the SyncSvcUtilUI.exe that allows you to create sql scripts for provision/deprovision/deprovisionstore. We use it (in production) to create the sync scope during an entity framework code first migration.

### CODE REVIEW

**Comment by gentledepp** [comment]
I also changed the "INSERT OR REPLACE" semantic when updating the local store with an "UPSERT" semantic. 
Basically, now there are 2 statements:
First "UPDATE OR IGNORE ..."
then "INSERT OR IGNORE..."

That way, when a client table has columns which are not synchronized (known to the sync scope) they will not be set to "null" (=> i.e. loose all data) when a server changeset is applied!

This was a very important change for us!

**Comment by gentledepp** [comment]
@Mimetis are you willing to merge?

**Comment by Mimetis** [comment]
thx for this commit ! :)

**Comment by gentledepp** [comment]
never mind. We are already using it in production and it works like charm.
Thank you for migrating to Xamarin in the first place - we owe you

**Pull request merged**
